=== shreya080527/Agrotravel-/src/main/webapp/feedbackSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="feedbacks">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="feedback" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="email" type="xs:string"/>
                            <xs:element name="product" type="xs:string"/>
                            <xs:element name="rating">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1"/>
                                        <xs:maxInclusive value="5"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="comment" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== shreya080527/Agrotravel-/src/main/webapp/feedbacks.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<feedbacks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="feedbackSchema.xsd">
        
    <feedback>
                
        <name>Dharshini</name>
                
        <email>dharshini@gmail.com</email>
                
        <product>Farm Honey</product>
                
        <rating>5</rating>
                
        <comment>Excellent quality and service.</comment>
            
    </feedback>
        
    <feedback>
                
        <name>Arun</name>
                
        <email>arun@gmail.com</email>
                
        <product>Organic Rice</product>
                
        <rating>4</rating>
                
        <comment>Good product and reasonable price.</comment>
            
    </feedback>
    
    <feedback>
        <name>Tester</name>
        <email>tester@agrotravel.com</email>
        <product>Farm Honey</product>
        <rating>5</rating>
        <comment>Outstanding flavor and purity.</comment>
    </feedback>
</feedbacks>
